import { Lecture } from '../types';

export const lesson1: Lecture = {
  id: "lec-001",
  title: "Understanding Business Correspondence",
  part: "Part 7",
  tags: ["Email", "Scheduling", "Formal Tone"],
  readingContent: `
  ### Subject: Update regarding the Q3 Marketing Strategy Meeting
  
  **From:** Sarah Jenkins, Director of Marketing  
  **To:** All Staff, Marketing Department  
  **Date:** October 12  
  
  Dear Team,
  
  Please be advised that the quarterly marketing strategy meeting, originally scheduled for this coming Monday, October 15, has been **postponed**. 
  
  Due to an unexpected conflict with the regional director's schedule, we have moved the meeting to **Wednesday, October 17 at 2:00 PM**. The location remains Conference Room B.
  
  Attendance is **mandatory** for all full-time employees. If you have a legitimate conflict with the new time, please contact my assistant, Mark, by end of day tomorrow.
  
  The updated **agenda** will be circulated later this afternoon. Please review it beforehand and come prepared with your team's progress reports.
  
  Thank you for your flexibility.
  
  Sincerely,  
  Sarah Jenkins
  `,
  vietnameseMeaningPassage: `
  ### Chủ đề: Cập nhật về cuộc họp Chiến lược Tiếp thị Quý 3
  
  **Từ:** Sarah Jenkins, Giám đốc Tiếp thị  
  **Gửi:** Toàn thể nhân viên, Phòng Tiếp thị  
  **Ngày:** 12 tháng 10  
  
  Gửi cả nhóm,
  
  Xin lưu ý rằng cuộc họp chiến lược tiếp thị hàng quý, ban đầu được lên lịch vào thứ Hai tới, ngày 15 tháng 10, đã bị **hoãn lại**.
  
  Do có sự xung đột lịch trình đột xuất với giám đốc khu vực, chúng tôi đã chuyển cuộc họp sang **thứ Tư, ngày 17 tháng 10 lúc 2:00 chiều**. Địa điểm vẫn là Phòng Họp B.
  
  Việc tham dự là **bắt buộc** đối với tất cả nhân viên toàn thời gian. Nếu bạn có lý do chính đáng không thể tham dự vào thời gian mới, vui lòng liên hệ với trợ lý của tôi, Mark, trước cuối ngày mai.
  
  **Chương trình nghị sự** cập nhật sẽ được gửi đi vào cuối buổi chiều nay. Vui lòng xem trước và chuẩn bị sẵn báo cáo tiến độ của nhóm bạn.
  
  Cảm ơn sự linh hoạt của các bạn.
  
  Trân trọng,  
  Sarah Jenkins
  `,
  keyTakeaways: [
    "Identify the main purpose of the email immediately (Schedule Change).",
    "Pay attention to details: New Date, Time, and Location.",
    "Look for synonyms in questions (e.g., 'mandatory' = 'required', 'postponed' = 'delayed').",
    "Note any required actions for the recipient (Contact Mark if there is a conflict).",
  ],
  vocabulary: [
    {
      word: "Résumé",
      ipa: "/ˈrez.juː.meɪ/",
      type: "n",
      meaning: "Sơ yếu lý lịch",
      example: "Fax your résumé and cover letter.",
    },

    {
      word: "Opening",
      ipa: "/ˈoʊ.pən.ɪŋ/",
      type: "n",
      meaning: "Vị trí trống, lễ khai trương",
      example: "Job openings at the restaurant.",
    },
    {
      word: "Vacancy",
      ipa: "/ˈveɪ.kən.si/",
      type: "n (syn)",
      meaning: "Khoảng trống, vị trí trống",
      example: "We have a vacancy.",
    },

    {
      word: "Applicant",
      ipa: "/ˈæp.lə.kənt/",
      type: "n",
      meaning: "Ứng viên",
      example: "Applicants are required to submit a résumé.",
    },
    {
      word: "Apply",
      ipa: "/əˈplaɪ/",
      type: "v (der)",
      meaning: "Ứng tuyển, áp dụng",
      example: "",
    },
    {
      word: "Application",
      ipa: "/ˌæp.ləˈkeɪ.ʃən/",
      type: "n (der)",
      meaning: "Đơn ứng tuyển",
      example: "",
    },
    {
      word: "Appliance",
      ipa: "/əˈplaɪ.əns/",
      type: "n",
      meaning: "Thiết bị, dụng cụ (dễ nhầm)",
      example: "Kitchen appliances.",
    },

    {
      word: "Requirement",
      ipa: "/rɪˈkwaɪr.mənt/",
      type: "n",
      meaning: "Yêu cầu, điều kiện",
      example: "A requirement of this job.",
    },
    {
      word: "Require",
      ipa: "/rɪˈkwaɪr/",
      type: "v (der)",
      meaning: "Yêu cầu",
      example: "",
    },
    {
      word: "Prerequisite",
      ipa: "/ˌpriːˈrek.wə.zɪt/",
      type: "n (syn)",
      meaning: "Điều kiện tiên quyết",
      example: "",
    },

    {
      word: "Meet",
      ipa: "/miːt/",
      type: "v",
      meaning: "Đáp ứng (nhu cầu/yêu cầu)",
      example: "Meet all the requirements.",
    },
    {
      word: "Satisfy",
      ipa: "/ˈsæt.ɪs.faɪ/",
      type: "v (syn)",
      meaning: "Thỏa mãn",
      example: "",
    },
    {
      word: "Fulfill",
      ipa: "/fʊlˈfɪl/",
      type: "v (syn)",
      meaning: "Hoàn thành",
      example: "",
    },

    {
      word: "Qualified",
      ipa: "/ˈkwɑː.lɪ.faɪd/",
      type: "adj",
      meaning: "Đủ khả năng, đủ điều kiện",
      example: "Qualified for the position.",
    },
    {
      word: "Qualify",
      ipa: "/ˈkwɑː.lɪ.faɪ/",
      type: "v (der)",
      meaning: "Đủ điều kiện",
      example: "",
    },
    {
      word: "Qualification",
      ipa: "/ˌkwɑː.lɪ.fɪˈkeɪ.ʃən/",
      type: "n (der)",
      meaning: "Bằng cấp, năng lực",
      example: "",
    },
    {
      word: "Certified",
      ipa: "/ˈsɜːr.tə.faɪd/",
      type: "adj (syn)",
      meaning: "Được chứng nhận",
      example: "",
    },

    {
      word: "Candidate",
      ipa: "/ˈkæn.dɪ.deɪt/",
      type: "n",
      meaning: "Thí sinh, ứng viên",
      example: "Five candidates selected.",
    },

    {
      word: "Confidence",
      ipa: "/ˈkɑːn.fɪ.dəns/",
      type: "n",
      meaning: "Sự tự tin, lòng tin",
      example: "Confidence in her ability.",
    },
    {
      word: "Confident",
      ipa: "/ˈkɑːn.fɪ.dənt/",
      type: "adj (der)",
      meaning: "Tự tin",
      example: "",
    },

    {
      word: "Highly",
      ipa: "/ˈhaɪ.li/",
      type: "adv",
      meaning: "Rất, hết sức",
      example: "Highly qualified.",
    },

    {
      word: "Professional",
      ipa: "/prəˈfeʃ.ən.əl/",
      type: "adj/n",
      meaning: "Chuyên nghiệp / Chuyên gia",
      example: "A professional photographer.",
    },
    {
      word: "Profession",
      ipa: "/prəˈfeʃ.ən/",
      type: "n (der)",
      meaning: "Nghề nghiệp",
      example: "",
    },

    {
      word: "Interview",
      ipa: "/ˈɪn.t̬ɚ.vjuː/",
      type: "n/v",
      meaning: "Phỏng vấn",
      example: "Interviews held in room 3.",
    },

    {
      word: "Hire",
      ipa: "/haɪr/",
      type: "v",
      meaning: "Thuê, tuyển dụng",
      example: "Hire new employees.",
    },

    {
      word: "Training",
      ipa: "/ˈtreɪ.nɪŋ/",
      type: "n",
      meaning: "Sự đào tạo",
      example: "On-the-job training.",
    },

    {
      word: "Reference",
      ipa: "/ˈref.ɚ.əns/",
      type: "n",
      meaning: "Sự giới thiệu, tham khảo",
      example: "Reference letter.",
    },
    {
      word: "Refer",
      ipa: "/rɪˈfɝː/",
      type: "v (der)",
      meaning: "Tham khảo, xem",
      example: "",
    },

    {
      word: "Position",
      ipa: "/pəˈzɪʃ.ən/",
      type: "n",
      meaning: "Vị trí, chức vụ",
      example: "The advertised position.",
    },

    {
      word: "Achievement",
      ipa: "/əˈtʃiːv.mənt/",
      type: "n",
      meaning: "Thành tựu",
      example: "List your achievements.",
    },
    {
      word: "Achiever",
      ipa: "/əˈtʃiː.vɚ/",
      type: "n (der)",
      meaning: "Người đạt thành tích",
      example: "",
    },

    {
      word: "Impressed",
      ipa: "/ɪmˈprest/",
      type: "adj",
      meaning: "Bị ấn tượng",
      example: "The CEO was impressed.",
    },
    {
      word: "Impressive",
      ipa: "/ɪmˈpres.ɪv/",
      type: "adj (der)",
      meaning: "Gây ấn tượng",
      example: "",
    },

    {
      word: "Excellent",
      ipa: "/ˈek.səl.ənt/",
      type: "adj",
      meaning: "Xuất sắc",
      example: "Excellent skills.",
    },

    {
      word: "Eligible",
      ipa: "/ˈel.ɪ.dʒə.bəl/",
      type: "adj",
      meaning: "Đủ tư cách, thích hợp",
      example: "Eligible for paid holidays.",
    },
    {
      word: "Ineligible",
      ipa: "/ɪnˈel.ɪ.dʒə.bəl/",
      type: "adj (ant)",
      meaning: "Không đủ tư cách",
      example: "",
    },

    {
      word: "Identify",
      ipa: "/ɑɪˈden.t̬ə.faɪ/",
      type: "v",
      meaning: "Nhận diện",
      example: "Easy to identify.",
    },
    {
      word: "Identification",
      ipa: "/ɑɪˌden.t̬ə.fəˈkeɪ.ʃən/",
      type: "n (der)",
      meaning: "Giấy tờ tùy thân",
      example: "",
    },

    {
      word: "Associate",
      ipa: "/əˈsoʊ.ʃi.eɪt/",
      type: "v",
      meaning: "Liên kết",
      example: "Associated with a competitor.",
    },
    {
      word: "Association",
      ipa: "/əˌsoʊ.siˈeɪ.ʃən/",
      type: "n (der)",
      meaning: "Hiệp hội, sự liên kết",
      example: "",
    },

    {
      word: "Condition",
      ipa: "/kənˈdɪʃ.ən/",
      type: "n",
      meaning: "Điều kiện",
      example: "Conditions of employment.",
    },

    {
      word: "Employment",
      ipa: "/ɪmˈplɔɪ.mənt/",
      type: "n",
      meaning: "Việc làm",
      example: "Employment opportunities.",
    },
    {
      word: "Employ",
      ipa: "/ɪmˈplɔɪ/",
      type: "v (der)",
      meaning: "Thuê",
      example: "",
    },
    {
      word: "Employee",
      ipa: "/ɪmˈplɔɪ.iː/",
      type: "n (der)",
      meaning: "Nhân viên",
      example: "",
    },
    {
      word: "Employer",
      ipa: "/ɪmˈplɔɪ.ɚ/",
      type: "n (der)",
      meaning: "Nhà tuyển dụng",
      example: "",
    },
    {
      word: "Unemployment",
      ipa: "/ˌʌn.ɪmˈplɔɪ.mənt/",
      type: "n (ant)",
      meaning: "Thất nghiệp",
      example: "",
    },

    {
      word: "Lack",
      ipa: "/læk/",
      type: "v/n",
      meaning: "Thiếu / Sự thiếu hụt",
      example: "Lack of funds.",
    },

    {
      word: "Managerial",
      ipa: "/ˌmæn.əˈdʒɪr.i.əl/",
      type: "adj",
      meaning: "Thuộc quản lý",
      example: "Managerial position.",
    },
    {
      word: "Manage",
      ipa: "/ˈmæn.ədʒ/",
      type: "v (der)",
      meaning: "Quản lý",
      example: "",
    },
    {
      word: "Supervisory",
      ipa: "/ˌsuː.pɚˈvaɪ.zɚ.i/",
      type: "adj (syn)",
      meaning: "Giám sát",
      example: "",
    },

    {
      word: "Diligent",
      ipa: "/ˈdɪl.ə.dʒənt/",
      type: "adj",
      meaning: "Siêng năng",
      example: "Diligent workers.",
    },
    {
      word: "Diligence",
      ipa: "/ˈdɪl.ə.dʒəns/",
      type: "n (der)",
      meaning: "Sự cần cù",
      example: "",
    },

    {
      word: "Familiar",
      ipa: "/fəˈmɪl.i.jɚ/",
      type: "adj",
      meaning: "Quen thuộc",
      example: "Become familiar with it.",
    },
    {
      word: "Unfamiliar",
      ipa: "/ʌn.fəˈmɪl.i.jɚ/",
      type: "adj (ant)",
      meaning: "Xa lạ",
      example: "",
    },

    {
      word: "Proficiency",
      ipa: "/prəˈfɪʃ.ən.si/",
      type: "n",
      meaning: "Sự thông thạo",
      example: "Proficiency in a language.",
    },
    {
      word: "Proficient",
      ipa: "/prəˈfɪʃ.ənt/",
      type: "adj (der)",
      meaning: "Thành thạo",
      example: "",
    },

    {
      word: "Prospective",
      ipa: "/prəˈspek.tɪv/",
      type: "adj",
      meaning: "Có triển vọng",
      example: "Prospective employees.",
    },
    {
      word: "Prospect",
      ipa: "/ˈprɑː.spekt/",
      type: "n (der)",
      meaning: "Triển vọng",
      example: "",
    },

    {
      word: "Appeal",
      ipa: "/əˈpiːl/",
      type: "v",
      meaning: "Thu hút, hấp dẫn",
      example: "Appealed to the staff.",
    },
    {
      word: "Attract",
      ipa: "/əˈtrækt/",
      type: "v (syn)",
      meaning: "Thu hút",
      example: "",
    },

    {
      word: "Specialize",
      ipa: "/ˈspeʃ.ə.laɪz/",
      type: "v",
      meaning: "Chuyên về",
      example: "Specialize in design.",
    },

    {
      word: "Apprehensive",
      ipa: "/ˌæp.rəˈhen.sɪv/",
      type: "adj",
      meaning: "Lo lắng, e sợ",
      example: "Feel apprehensive.",
    },
    {
      word: "Concerned",
      ipa: "/kənˈsɝːnd/",
      type: "adj (syn)",
      meaning: "Lo ngại",
      example: "",
    },

    {
      word: "Consultant",
      ipa: "/kənˈsʌl.tənt/",
      type: "n",
      meaning: "Cố vấn",
      example: "Design consultant.",
    },
    {
      word: "Consult",
      ipa: "/kənˈsʌlt/",
      type: "v (der)",
      meaning: "Hỏi ý kiến",
      example: "",
    },

    {
      word: "Entitle",
      ipa: "/ɪnˈtaɪ.t̬əl/",
      type: "v",
      meaning: "Cho quyền",
      example: "Entitled to benefits.",
    },

    {
      word: "Degree",
      ipa: "/dɪˈɡriː/",
      type: "n",
      meaning: "Bằng cấp, độ",
      example: "Bachelor's degree.",
    },

    {
      word: "Payroll",
      ipa: "/ˈpeɪ.roʊl/",
      type: "n",
      meaning: "Bảng lương",
      example: "Added to the payroll.",
    },

    {
      word: "Recruit",
      ipa: "/rɪˈkruːt/",
      type: "v/n",
      meaning: "Tuyển dụng",
      example: "Recruits graduates.",
    },
    {
      word: "Recruitment",
      ipa: "/rɪˈkruːt.mənt/",
      type: "n (der)",
      meaning: "Sự tuyển dụng",
      example: "",
    },

    {
      word: "Certification",
      ipa: "/ˌsɝː.t̬ə.fəˈkeɪ.ʃən/",
      type: "n",
      meaning: "Giấy chứng nhận",
      example: "Accounting certification.",
    },
    {
      word: "Certify",
      ipa: "/ˈsɝː.t̬ə.faɪ/",
      type: "v (der)",
      meaning: "Chứng nhận",
      example: "",
    },
    {
      word: "Certificate",
      ipa: "/sɚˈtɪf.ɪ.kət/",
      type: "n (der)",
      meaning: "Chứng chỉ",
      example: "",
    },

    {
      word: "Occupation",
      ipa: "/ˌɑː.kjəˈpeɪ.ʃən/",
      type: "n",
      meaning: "Nghề nghiệp",
      example: "Challenging occupation.",
    },
    {
      word: "Occupy",
      ipa: "/ˈɑː.kjə.paɪ/",
      type: "v (der)",
      meaning: "Chiếm giữ",
      example: "",
    },
    {
      word: "Occupant",
      ipa: "/ˈɑː.kjə.pənt/",
      type: "n (der)",
      meaning: "Người cư trú/sử dụng",
      example: "",
    },

    {
      word: "Wage",
      ipa: "/weɪdʒ/",
      type: "n",
      meaning: "Tiền công (giờ/tuần)",
      example: "Earn higher wages.",
    },
    {
      word: "Salary",
      ipa: "/ˈsæl.ɚ.i/",
      type: "n (syn)",
      meaning: "Tiền lương (tháng/năm)",
      example: "",
    },
    {
      word: "Compensation",
      ipa: "/ˌkɑːm.penˈseɪ.ʃən/",
      type: "n (syn)",
      meaning: "Thù lao, bồi thường",
      example: "",
    },

    // --- BASIC & PHRASES (Bổ sung đầy đủ) ---
    {
      word: "Application form",
      ipa: "",
      type: "phr",
      meaning: "Mẫu đơn xin việc",
      example: "",
    },
    {
      word: "Career",
      ipa: "/kəˈrɪr/",
      type: "n",
      meaning: "Sự nghiệp",
      example: "",
    },
    {
      word: "Completion",
      ipa: "/kəmˈpliː.ʃən/",
      type: "n",
      meaning: "Sự hoàn thành",
      example: "",
    },
    {
      word: "Fair",
      ipa: "/fer/",
      type: "adj",
      meaning: "Công bằng",
      example: "",
    },
    {
      word: "Graduation",
      ipa: "/ˌɡrædʒ.uˈeɪ.ʃən/",
      type: "n",
      meaning: "Sự tốt nghiệp",
      example: "",
    },
    {
      word: "In fact",
      ipa: "",
      type: "phr",
      meaning: "Trong thực tế",
      example: "",
    },
    {
      word: "Job fair",
      ipa: "",
      type: "phr",
      meaning: "Hội chợ việc làm",
      example: "",
    },
    {
      word: "Job offer",
      ipa: "",
      type: "phr",
      meaning: "Lời mời làm việc",
      example: "",
    },
    {
      word: "List",
      ipa: "/lɪst/",
      type: "n",
      meaning: "Danh sách",
      example: "",
    },
    {
      word: "Newcomer",
      ipa: "/ˈnuːˌkʌm.ɚ/",
      type: "n",
      meaning: "Người mới",
      example: "",
    },
    {
      word: "Part-time",
      ipa: "",
      type: "adj",
      meaning: "Bán thời gian",
      example: "",
    },
    {
      word: "Previous job",
      ipa: "",
      type: "phr",
      meaning: "Công việc trước đây",
      example: "",
    },
    {
      word: "Secretary",
      ipa: "/ˈsek.rə.ter.i/",
      type: "n",
      meaning: "Thư ký",
      example: "",
    },
    {
      word: "Send in",
      ipa: "",
      type: "phr",
      meaning: "Nộp, giao",
      example: "",
    },
    {
      word: "Tidy",
      ipa: "/ˈtaɪ.di/",
      type: "adj",
      meaning: "Gọn gàng",
      example: "",
    },
    {
      word: "Trainee",
      ipa: "/ˌtreɪˈniː/",
      type: "n",
      meaning: "Thực tập sinh",
      example: "",
    },
    {
      word: "Apply for",
      ipa: "",
      type: "phr",
      meaning: "Ứng tuyển vào",
      example: "",
    },
    {
      word: "Aptitude",
      ipa: "/ˈæp.tə.tuːd/",
      type: "n",
      meaning: "Năng khiếu",
      example: "",
    },
    {
      word: "Be admitted to",
      ipa: "",
      type: "phr",
      meaning: "Được nhận vào",
      example: "",
    },
    {
      word: "Be advised to do",
      ipa: "",
      type: "phr",
      meaning: "Được khuyên làm gì",
      example: "",
    },
    {
      word: "Criteria",
      ipa: "/kraɪˈtɪr.i.ə/",
      type: "n",
      meaning: "Tiêu chuẩn (số nhiều)",
      example: "",
    },
    {
      word: "Decade",
      ipa: "/dekˈeɪd/",
      type: "n",
      meaning: "Thập kỷ",
      example: "",
    },
    {
      word: "Insufficient",
      ipa: "/ˌɪn.səˈfɪʃ.ənt/",
      type: "adj",
      meaning: "Không đủ",
      example: "",
    },
    {
      word: "Minimum",
      ipa: "/ˈmɪn.ə.məm/",
      type: "adj",
      meaning: "Tối thiểu",
      example: "",
    },
    {
      word: "Party",
      ipa: "/ˈpɑːr.t̬i/",
      type: "n",
      meaning: "Bữa tiệc, nhóm",
      example: "",
    },
    {
      word: "Plentiful",
      ipa: "/ˈplen.t̬ɪ.fəl/",
      type: "adj",
      meaning: "Dồi dào",
      example: "",
    },

    // --- 800 LEVEL ---
    {
      word: "Achieve one's goal",
      ipa: "",
      type: "phr",
      meaning: "Đạt mục tiêu",
      example: "",
    },
    {
      word: "Apprentice",
      ipa: "/əˈpren.t̬ɪs/",
      type: "n",
      meaning: "Người học việc",
      example: "",
    },
    {
      word: "Dress formally",
      ipa: "",
      type: "phr",
      meaning: "Ăn mặc trang trọng",
      example: "",
    },
    {
      word: "Dressed in suit",
      ipa: "",
      type: "phr",
      meaning: "Mặc vest",
      example: "",
    },
    {
      word: "Figure out",
      ipa: "",
      type: "phr",
      meaning: "Tìm ra, phát hiện ra",
      example: "",
    },
    {
      word: "Full time work",
      ipa: "",
      type: "phr",
      meaning: "Công việc toàn thời gian",
      example: "",
    },
    {
      word: "Job opportunity",
      ipa: "",
      type: "phr",
      meaning: "Cơ hội việc làm",
      example: "",
    },
    {
      word: "Job search",
      ipa: "",
      type: "phr",
      meaning: "Tìm kiếm việc làm",
      example: "",
    },
    {
      word: "Job seeker",
      ipa: "",
      type: "phr",
      meaning: "Người tìm việc",
      example: "",
    },
    {
      word: "Lay out",
      ipa: "",
      type: "phr",
      meaning: "Đặt ra, bày ra",
      example: "",
    },
    {
      word: "Letter of recommendation",
      ipa: "",
      type: "phr",
      meaning: "Thư giới thiệu",
      example: "",
    },
    {
      word: "Pay raise",
      ipa: "",
      type: "phr",
      meaning: "Sự tăng lương",
      example: "",
    },
    {
      word: "Practical experience",
      ipa: "",
      type: "phr",
      meaning: "Kinh nghiệm thực tế",
      example: "",
    },
    {
      word: "Proof of employment",
      ipa: "",
      type: "phr",
      meaning: "Bằng chứng công việc",
      example: "",
    },
    {
      word: "Reapply",
      ipa: "/ˌriː.əˈplaɪ/",
      type: "v",
      meaning: "Ứng tuyển lại",
      example: "",
    },
    {
      word: "Recommendation letter",
      ipa: "",
      type: "phr",
      meaning: "Thư tiến cử",
      example: "",
    },
    {
      word: "Reference letter",
      ipa: "",
      type: "phr",
      meaning: "Thư giới thiệu",
      example: "",
    },
    {
      word: "Send off to",
      ipa: "",
      type: "phr",
      meaning: "Gửi tới",
      example: "",
    },
    {
      word: "Set up an interview",
      ipa: "",
      type: "phr",
      meaning: "Sắp xếp phỏng vấn",
      example: "",
    },
    {
      word: "Take an examination",
      ipa: "",
      type: "phr",
      meaning: "Làm bài kiểm tra",
      example: "",
    },
    {
      word: "Training center",
      ipa: "",
      type: "phr",
      meaning: "Trung tâm đào tạo",
      example: "",
    },
    {
      word: "Waiting room",
      ipa: "",
      type: "phr",
      meaning: "Phòng chờ",
      example: "",
    },
    {
      word: "Well-educated",
      ipa: "",
      type: "adj",
      meaning: "Có học thức",
      example: "",
    },
    {
      word: "Workstation",
      ipa: "/ˈwɝːkˌsteɪ.ʃən/",
      type: "n",
      meaning: "Chỗ ngồi làm việc",
      example: "",
    },
    {
      word: "Zealous",
      ipa: "/ˈzel.əs/",
      type: "adj",
      meaning: "Hăng hái",
      example: "",
    },
    {
      word: "Cover letter",
      ipa: "",
      type: "phr",
      meaning: "Thư xin việc",
      example: "",
    },
    {
      word: "Devoted",
      ipa: "/dɪˈvoʊ.t̬ɪd/",
      type: "adj",
      meaning: "Tận tâm",
      example: "",
    },
    {
      word: "Energetic",
      ipa: "/ˌen.ɚˈdʒet̬.ɪk/",
      type: "adj",
      meaning: "Năng động",
      example: "",
    },
    {
      word: "Enthusiastic",
      ipa: "/ɪnˌθuː.ziˈæs.tɪk/",
      type: "adj",
      meaning: "Nhiệt tình",
      example: "",
    },
    {
      word: "Excel",
      ipa: "/ɪkˈsel/",
      type: "v",
      meaning: "Xuất sắc",
      example: "",
    },
    {
      word: "Exclude",
      ipa: "/ɪkˈskluːd/",
      type: "v",
      meaning: "Loại trừ",
      example: "",
    },
    {
      word: "Fluently",
      ipa: "/ˈfluː.ənt.li/",
      type: "adv",
      meaning: "Trôi chảy",
      example: "",
    },
    {
      word: "Get through",
      ipa: "",
      type: "phr",
      meaning: "Vượt qua, đỗ",
      example: "",
    },

    // --- PART 7 ---
    {
      word: "Match",
      ipa: "/mætʃ/",
      type: "v",
      meaning: "Hợp với, xứng với",
      example: "",
    },
    {
      word: "Necessity",
      ipa: "/nəˈses.ə.t̬i/",
      type: "n",
      meaning: "Sự cần thiết",
      example: "",
    },
    {
      word: "Qualification",
      ipa: "/ˌkwɑː.lɪ.fɪˈkeɪ.ʃən/",
      type: "n",
      meaning: "Năng lực, bằng cấp",
      example: "",
    },
    {
      word: "Relevant",
      ipa: "/ˈrel.ə.vənt/",
      type: "adj",
      meaning: "Liên quan",
      example: "",
    },
    {
      word: "Sign up for",
      ipa: "",
      type: "phr",
      meaning: "Đăng ký",
      example: "",
    },
    {
      word: "Talented",
      ipa: "/ˈtæl.ən.t̬ɪd/",
      type: "adj",
      meaning: "Có tài",
      example: "",
    },
    {
      word: "Visiting",
      ipa: "/ˈvɪz.ɪ.tɪŋ/",
      type: "n/adj",
      meaning: "Sự thăm viếng",
      example: "",
    },
    {
      word: "Workforce",
      ipa: "/ˈwɝːk.fɔːrs/",
      type: "n",
      meaning: "Lực lượng lao động",
      example: "",
    },
    {
      word: "Address the audience",
      ipa: "",
      type: "phr",
      meaning: "Giao lưu khán giả",
      example: "",
    },
    {
      word: "Be influenced by appearance",
      ipa: "",
      type: "phr",
      meaning: "Bị chi phối bởi vẻ ngoài",
      example: "",
    },
    {
      word: "Bilingual",
      ipa: "/baɪˈlɪŋ.ɡwəl/",
      type: "adj",
      meaning: "Song ngữ",
      example: "",
    },
    {
      word: "Curriculum vitae",
      ipa: "",
      type: "phr",
      meaning: "Sơ yếu lý lịch",
      example: "",
    },
    {
      word: "Diploma",
      ipa: "/dɪˈploʊ.mə/",
      type: "n",
      meaning: "Bằng tốt nghiệp",
      example: "",
    },
    {
      word: "Endurance",
      ipa: "/ɪnˈdʊr.əns/",
      type: "n",
      meaning: "Sự chịu đựng",
      example: "",
    },
    {
      word: "External",
      ipa: "/ɪkˈstɝː.nəl/",
      type: "adj",
      meaning: "Bên ngoài",
      example: "",
    },
    {
      word: "Fluency",
      ipa: "/ˈfluː.ən.si/",
      type: "n",
      meaning: "Sự trôi chảy",
      example: "",
    },
    {
      word: "Fluent in",
      ipa: "",
      type: "phr",
      meaning: "Thành thạo về",
      example: "",
    },
    {
      word: "Human resources",
      ipa: "",
      type: "phr",
      meaning: "Nhân sự",
      example: "",
    },
    {
      word: "Improperly",
      ipa: "/ɪmˈprɑː.pɚ.li/",
      type: "adv",
      meaning: "Không đúng cách",
      example: "",
    },
    {
      word: "In a positive manner",
      ipa: "",
      type: "phr",
      meaning: "Theo cách tích cực",
      example: "",
    },
    {
      word: "In the field of",
      ipa: "",
      type: "phr",
      meaning: "Trong lĩnh vực",
      example: "",
    },
    {
      word: "Inexperience",
      ipa: "/ˌɪn.ɪkˈspɪr.i.əns/",
      type: "n",
      meaning: "Thiếu kinh nghiệm",
      example: "",
    },
    {
      word: "Lack confidence",
      ipa: "",
      type: "phr",
      meaning: "Thiếu tự tin",
      example: "",
    },
    {
      word: "Make A a regular habit",
      ipa: "",
      type: "phr",
      meaning: "Biến A thành thói quen",
      example: "",
    },
    {
      word: "Make a commitment to",
      ipa: "",
      type: "phr",
      meaning: "Cam kết với",
      example: "",
    },
    {
      word: "Make a point of",
      ipa: "",
      type: "phr",
      meaning: "Tận tâm với",
      example: "",
    },
    {
      word: "Manpower",
      ipa: "/ˈmænˌpaʊ.ɚ/",
      type: "n",
      meaning: "Nhân lực",
      example: "",
    },
    {
      word: "Master's degree",
      ipa: "",
      type: "phr",
      meaning: "Bằng thạc sĩ",
      example: "",
    },
    {
      word: "Novice",
      ipa: "/ˈnɑː.vɪs/",
      type: "n",
      meaning: "Người tập sự",
      example: "",
    },
    {
      word: "Paycheck",
      ipa: "/ˈpeɪ.tʃek/",
      type: "n",
      meaning: "Tiền lương",
      example: "",
    },
    {
      word: "Self-motivation",
      ipa: "",
      type: "n",
      meaning: "Sự tự tạo động lực",
      example: "",
    },
    {
      word: "Send a notification",
      ipa: "",
      type: "phr",
      meaning: "Gửi thông báo",
      example: "",
    },
    {
      word: "Vacancy",
      ipa: "/ˈveɪ.kən.si/",
      type: "n",
      meaning: "Vị trí trống",
      example: "",
    },
    {
      word: "Wanted",
      ipa: "/ˈwɑːn.t̬ɪd/",
      type: "adj",
      meaning: "Được cần đến",
      example: "",
    },
    {
      word: "Work history",
      ipa: "",
      type: "phr",
      meaning: "Lịch sử làm việc",
      example: "",
    },

    // --- 900 LEVEL ---
    {
      word: "Credential",
      ipa: "/krɪˈden.ʃəl/",
      type: "n",
      meaning: "Chứng chỉ/Uy tín",
      example: "",
    },
    {
      word: "Firsthand",
      ipa: "/ˈfɝːst.hænd/",
      type: "adj",
      meaning: "Trực tiếp",
      example: "",
    },
    {
      word: "Hiring committee",
      ipa: "",
      type: "phr",
      meaning: "Ủy ban tuyển dụng",
      example: "",
    },
    {
      word: "Not to mention",
      ipa: "",
      type: "phr",
      meaning: "Chưa kể đến",
      example: "",
    },
    {
      word: "On occasion",
      ipa: "",
      type: "phr",
      meaning: "Thỉnh thoảng",
      example: "",
    },
    {
      word: "Overqualified",
      ipa: "/ˌoʊ.vɚˈkwɑː.lə.faɪd/",
      type: "adj",
      meaning: "Thừa năng lực",
      example: "",
    },
    {
      word: "Screening",
      ipa: "/ˈskriː.nɪŋ/",
      type: "n",
      meaning: "Sự sàng lọc",
      example: "",
    },
    { word: "Lag", ipa: "/læɡ/", type: "v", meaning: "Chậm trễ", example: "" },
    {
      word: "On the waiting list",
      ipa: "",
      type: "phr",
      meaning: "Trong danh sách chờ",
      example: "",
    },
    {
      word: "Oriented",
      ipa: "/ˈɔːr.i.en.t̬ɪd/",
      type: "adj",
      meaning: "Được định hướng",
      example: "",
    },
    {
      word: "Pertaining to",
      ipa: "",
      type: "phr",
      meaning: "Gắn liền với",
      example: "",
    },
    {
      word: "Questionably",
      ipa: "/ˈkwes.tʃə.nə.bli/",
      type: "adv",
      meaning: "Đáng ngờ",
      example: "",
    },
    {
      word: "Regularity",
      ipa: "/ˌreɡ.jəˈler.ə.t̬i/",
      type: "n",
      meaning: "Sự đều đặn",
      example: "",
    },
    {
      word: "Replenish",
      ipa: "/rɪˈplen.ɪʃ/",
      type: "v",
      meaning: "Làm đầy lại",
      example: "",
    },
    {
      word: "Simplicity",
      ipa: "/sɪmˈplɪs.ə.t̬i/",
      type: "n",
      meaning: "Sự đơn giản",
      example: "",
    },
    {
      word: "Stellar",
      ipa: "/ˈstel.ɚ/",
      type: "adj",
      meaning: "Xuất sắc",
      example: "",
    },
    {
      word: "Versatile",
      ipa: "/ˈvɝː.sə.t̬əl/",
      type: "adj",
      meaning: "Linh hoạt",
      example: "",
    },
    {
      word: "Adept",
      ipa: "/əˈdept/",
      type: "adj",
      meaning: "Tinh thông",
      example: "",
    },
    {
      word: "Against all odds",
      ipa: "",
      type: "phr",
      meaning: "Bất chấp khó khăn",
      example: "",
    },
    {
      word: "Command",
      ipa: "/kəˈmænd/",
      type: "n",
      meaning: "Quyền chỉ huy",
      example: "",
    },
    {
      word: "Commensurate",
      ipa: "/kəˈmen.sjɚ.ət/",
      type: "adj",
      meaning: "Tương xứng",
      example: "",
    },
    {
      word: "Computer literate",
      ipa: "",
      type: "phr",
      meaning: "Biết dùng máy tính",
      example: "",
    },
    {
      word: "Eagerness",
      ipa: "/ˈiː.ɡɚ.nəs/",
      type: "n",
      meaning: "Sự háo hức",
      example: "",
    },
    {
      word: "Familiarize oneself with",
      ipa: "",
      type: "phr",
      meaning: "Tự làm quen với",
      example: "",
    },
    {
      word: "Increment",
      ipa: "/ˈɪŋ.krə.mənt/",
      type: "n",
      meaning: "Sự gia tăng",
      example: "",
    },
    {
      word: "Interpersonal skills",
      ipa: "",
      type: "phr",
      meaning: "Kỹ năng mềm",
      example: "",
    },
    {
      word: "Mindful",
      ipa: "/ˈmaɪnd.fəl/",
      type: "adj",
      meaning: "Lưu tâm",
      example: "",
    },
    {
      word: "Preeminent",
      ipa: "/priːˈem.ə.nənt/",
      type: "adj",
      meaning: "Ưu việt",
      example: "",
    },
    {
      word: "Preliminary",
      ipa: "/prɪˈlɪm.ə.ner.i/",
      type: "adj",
      meaning: "Sơ bộ",
      example: "",
    },
    {
      word: "Prerequisite",
      ipa: "/ˌpriːˈrek.wə.zɪt/",
      type: "n",
      meaning: "Tiên quyết",
      example: "",
    },
    {
      word: "Probationer",
      ipa: "/proʊˈbeɪ.ʃən.ɚ/",
      type: "n",
      meaning: "Nhân viên tập sự",
      example: "",
    },
    {
      word: "Sternly",
      ipa: "/ˈstɝːn.li/",
      type: "adv",
      meaning: "Nghiêm khắc",
      example: "",
    },
  ],
  exercises: [
    {
      id: "q1",
      question: "What is the main purpose of the email?",
      options: [
        { id: "A", text: "To announce a new marketing director" },
        { id: "B", text: "To reschedule a planned meeting" },
        { id: "C", text: "To discuss the Q3 budget" },
        { id: "D", text: "To invite staff to a social event" },
      ],
      correctOptionId: "B",
      explanation:
        "The email explicitly states that the meeting 'has been postponed' and moved to a new date. Therefore, the purpose is to reschedule.",
    },
    {
      id: "q2",
      question: "When is the new time for the meeting?",
      options: [
        { id: "A", text: "Monday, October 15" },
        { id: "B", text: "Tuesday, October 16" },
        { id: "C", text: "Wednesday, October 17" },
        { id: "D", text: "Thursday, October 18" },
      ],
      correctOptionId: "C",
      explanation:
        "The text states: 'we have moved the meeting to Wednesday, October 17'.",
    },
    {
      id: "q3",
      question: "What should employees do if they cannot attend?",
      options: [
        { id: "A", text: "Email Sarah Jenkins directly" },
        { id: "B", text: "Skip the meeting without notice" },
        { id: "C", text: "Contact Mark by tomorrow" },
        { id: "D", text: "Attend the meeting anyway" },
      ],
      correctOptionId: "C",
      explanation:
        "The email says: 'please contact my assistant, Mark, by end of day tomorrow' if there is a conflict.",
    },
  ],
};
